[options]
addons_path = /mnt/extra-addons, /opt/odoo/addons, /opt/odoo/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$YCzFeA/hvPf.X8sZQ8i59w$eq32CMS5sxZaHLNrD/Huhn0zrUGt/yhX6XDDzh2qGAKHUWicjCOBa5rhQE3.M37or3llDK3pygtdmgJTmLNE5Q
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo.log
proxy_mode = True
csv_internal_sep = ,
without_demo = False
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
