[options]
addons_path = /mnt/extra-addons, /opt/odoo/addons, /opt/odoo/odoo/addons
admin_passwd = admin
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo.log
proxy_mode = True
csv_internal_sep = ,
without_demo = False

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
